package

public inline fun myCatchIOException(/*0*/ block: () -> kotlin.Unit): kotlin.Unit
    CallsInPlace(block, EXACTLY_ONCE)
    blockkotlin.Unit provides Catches IOException

public inline fun myCatchRuntimeException(/*0*/ block: () -> kotlin.Unit): kotlin.Unit
    CallsInPlace(block, EXACTLY_ONCE)
    blockkotlin.Unit provides Catches RuntimeException

public fun test_1(): kotlin.Unit
public fun test_2(): kotlin.Unit
public fun test_3(): kotlin.Unit
public fun throwsFileNotFoundException(): kotlin.Unit
    throwsFileNotFoundExceptionkotlin.Unit verifies Catches FileNotFoundException

public fun throwsIOException(): kotlin.Unit
    throwsIOExceptionkotlin.Unit verifies Catches IOException

public fun throwsNullPointerException(): kotlin.Unit
    throwsNullPointerExceptionkotlin.Unit verifies Catches NullPointerException
